import { DevKitCliBuilder } from "./DevKItCliBuilder";
import { DevKitCliCommandRegistry } from "./DevKitCommandRegistry";

export const SERVICES = {
    DEV_KIT_CLI: 'DevKitCli',
    EVENT_LOGGER: 'IEventLogger',
    EVENT_LOGGER_EX: 'IEventLoggerEx',
    EVENT_LOGGER_FACTORY: 'IEventLoggerFactory',
    EVENT_LOGGER_FACTORY_EX: 'IEventLoggerFactoryEx',
    DEV_KIT_CLI_COMMAND: 'IDevKitCliCommand',
    DEV_KIT_CLI_COMMAND_FACTORY: 'Factory<IDevKitCliCommand>',
    DEV_KIT_CLI_COMMAND_REGISTRY: DevKitCliCommandRegistry,
    //DEV_KIT_CLI_BUILDER: DevKitCliBuilder,
    DEV_KIT_IMMEDIATE_CLI_FACTORY: 'DEV_KIT_IMMEDIATE_CLI_FACTORY',
    DEV_KIT_INTERACTIVE_CLI_FACTORY: 'DEV_KIT_INTERACTIVE_CLI_FACTORY',
    DEV_KIT_IMMEDIATE_CLI_FACTORY_FACTORY: 'DEV_KIT_IMMEDIATE_CLI_FACTORY_FACTORY',
    DEV_KIT_INTERACTIVE_CLI_FACTORY_FACTORY: 'DEV_KIT_INTERACTIVE_CLI_FACTORY_FACTORY',
    DEV_KIT_CLI_COMMAND_MAP_FACTORY: 'DEV_KIT_CLI_COMMAND_MAP'
}